# import

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.5.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\Users\VED\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "c:\Users\VED\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "c:\Users\VED\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "c:\Users\VED\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "c:\Users\VED\anaconda3\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "c:\Users\VED\anaconda3\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "c:\Users\VED\anaconda3\Lib\asyncio\base_events.py", line 1986, in _run_once
    handle._run()
  File "c:\Users\VED\anaconda3\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\VED\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "c:\Users\VED\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "c:\Users\VED\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "c:\Users\VED\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "c:\Users\VED\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "c:\Users\VED\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\Users\VED\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "c:\Users\VED\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "c:\Users\VED\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "c:\Users\VED\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\Users\VED\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "c:\Users\VED\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\VED\AppData\Local\Temp\ipykernel_14592\555797462.py", line 1, in <module>
    import pandas as pd
  File "c:\Users\VED\anaconda3\Lib\site-packages\pandas\__init__.py", line 34, in <module>
    from pandas.compat import (
  File "c:\Users\VED\anaconda3\Lib\site-packages\pandas\compat\__init__.py", line 28, in <module>
    from pandas.compat.pyarrow import (
  File "c:\Users\VED\anaconda3\Lib\site-packages\pandas\compat\pyarrow.py", line 12, in <module>
    import pyarrow as pa
  File "c:\Users\VED\anaconda3\Lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.5.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.5.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\Users\VED\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "c:\Users\VED\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "c:\Users\VED\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "c:\Users\VED\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "c:\Users\VED\anaconda3\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "c:\Users\VED\anaconda3\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "c:\Users\VED\anaconda3\Lib\asyncio\base_events.py", line 1986, in _run_once
    handle._run()
  File "c:\Users\VED\anaconda3\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\VED\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "c:\Users\VED\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "c:\Users\VED\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "c:\Users\VED\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "c:\Users\VED\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "c:\Users\VED\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\Users\VED\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "c:\Users\VED\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "c:\Users\VED\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "c:\Users\VED\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\Users\VED\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "c:\Users\VED\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\VED\AppData\Local\Temp\ipykernel_14592\555797462.py", line 1, in <module>
    import pandas as pd
  File "c:\Users\VED\anaconda3\Lib\site-packages\pandas\__init__.py", line 58, in <module>
    from pandas.core.api import (
  File "c:\Users\VED\anaconda3\Lib\site-packages\pandas\core\api.py", line 27, in <module>
    from pandas.core.arrays import Categorical
  File "c:\Users\VED\anaconda3\Lib\site-packages\pandas\core\arrays\__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "c:\Users\VED\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "c:\Users\VED\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\array.py", line 64, in <module>
    from pandas.core import (
  File "c:\Users\VED\anaconda3\Lib\site-packages\pandas\core\ops\__init__.py", line 9, in <module>
    from pandas.core.ops.array_ops import (
  File "c:\Users\VED\anaconda3\Lib\site-packages\pandas\core\ops\array_ops.py", line 55, in <module>
    from pandas.core.computation import expressions
  File "c:\Users\VED\anaconda3\Lib\site-packages\pandas\core\computation\expressions.py", line 23, in <module>
    from pandas.core.computation.check import NUMEXPR_INSTALLED
  File "c:\Users\VED\anaconda3\Lib\site-packages\pandas\core\computation\check.py", line 5, in <module>
    ne = import_optional_dependency("numexpr", errors="warn")
  File "c:\Users\VED\anaconda3\Lib\site-packages\pandas\compat\_optional.py", line 158, in import_optional_dependency
    module = importlib.import_module(name)
  File "c:\Users\VED\anaconda3\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "c:\Users\VED\anaconda3\Lib\site-packages\numexpr\__init__.py", line 24, in <module>
    from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.5.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\Users\VED\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "c:\Users\VED\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "c:\Users\VED\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "c:\Users\VED\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "c:\Users\VED\anaconda3\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "c:\Users\VED\anaconda3\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "c:\Users\VED\anaconda3\Lib\asyncio\base_events.py", line 1986, in _run_once
    handle._run()
  File "c:\Users\VED\anaconda3\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\VED\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "c:\Users\VED\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "c:\Users\VED\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "c:\Users\VED\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "c:\Users\VED\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "c:\Users\VED\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\Users\VED\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "c:\Users\VED\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "c:\Users\VED\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "c:\Users\VED\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\Users\VED\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "c:\Users\VED\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\VED\AppData\Local\Temp\ipykernel_14592\555797462.py", line 1, in <module>
    import pandas as pd
  File "c:\Users\VED\anaconda3\Lib\site-packages\pandas\__init__.py", line 58, in <module>
    from pandas.core.api import (
  File "c:\Users\VED\anaconda3\Lib\site-packages\pandas\core\api.py", line 27, in <module>
    from pandas.core.arrays import Categorical
  File "c:\Users\VED\anaconda3\Lib\site-packages\pandas\core\arrays\__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "c:\Users\VED\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "c:\Users\VED\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\array.py", line 78, in <module>
    from pandas.core.arrays.masked import BaseMaskedArray
  File "c:\Users\VED\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py", line 56, in <module>
    from pandas.core import (
  File "c:\Users\VED\anaconda3\Lib\site-packages\pandas\core\nanops.py", line 54, in <module>
    bn = import_optional_dependency("bottleneck", errors="warn")
  File "c:\Users\VED\anaconda3\Lib\site-packages\pandas\compat\_optional.py", line 158, in import_optional_dependency
    module = importlib.import_module(name)
  File "c:\Users\VED\anaconda3\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "c:\Users\VED\anaconda3\Lib\site-packages\bottleneck\__init__.py", line 7, in <module>
    from .move import (move_argmax, move_argmin, move_max, move_mean, move_median,

ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.5.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

# loading the dataset

In [3]:
customers=pd.read_csv('F:/data science/e-comerence-analysis/data/raw/customers.csv')
order_items=pd.read_csv('F:/data science/e-comerence-analysis/data/raw/order_items.csv')
orders=pd.read_csv('F:/data science/e-comerence-analysis/data/raw/orders.csv')
products=pd.read_csv('F:/data science/e-comerence-analysis/data/raw/products.csv')

In [4]:
customers.head()

   customer_id signup_date state acquisition_channel
0            1  2024-09-13    CO      organic_search
1            2  2025-10-21    IL         paid_search
2            3  2025-01-17    AZ            referral
3            4  2024-06-23    FL         paid_social
4            5  2025-04-08    IL         paid_social

In [5]:
order_items.head()

   order_id  product_id  quantity  unit_price  discount_amount
0    100001        1031         1       38.99              0.0
1    100002        1087         1       45.99              0.0
2    100002        1072         1      141.99              0.0
3    100003        1048         1      139.99              0.0
4    100004        1083         1       19.99              2.0

In [6]:
orders.head()

,order_id,customer_id,order_date,status,payment_method,discount_code,shipping_fee
0,100001,1530,2024-01-01 09:24:45,completed,credit_card,NaN,6.95
1,100002,3531,2024-01-01 10:37:49,completed,credit_card,NaN,0.00
2,100003,840,2024-01-01 10:59:09,completed,credit_card,NaN,0.00
3,100004,725,2024-01-01 12:48:34,completed,apple_pay,WELCOME10,0.00
4,100005,3452,2024-01-01 17:44:03,completed,gift_card,NaN,0.00

In [7]:
products.head()

   product_id            product_name  category  list_price  unit_cost
0        1001        Brass Chef Knife   Kitchen       61.99      38.13
1        1002    Walnut Cutting Board   Kitchen      138.99      74.76
2        1003  Matte Black Dutch Oven   Kitchen       22.99      13.50
3        1004         Classic Skillet   Kitchen       75.99      39.86
4        1005   Linen Mixing Bowl Set  Kitchen        79.99      41.11

## shape

In [8]:
print(f'customers {customers.shape}, order items {order_items.shape}, orders {orders.shape}, products {products.shape}')

customers (3600, 4), order items (15608, 5), orders (9245, 7), products (90, 5)

## columns

In [9]:
print("CUSTOMERS")
print(customers.columns.tolist())

print("\nORDERS")
print(orders.columns.tolist())

print("\nORDER ITEMS")
print(order_items.columns.tolist())

print("\nPRODUCTS")
print(products.columns.tolist())

CUSTOMERS
['customer_id', 'signup_date', 'state', 'acquisition_channel']

ORDERS
['order_id', 'customer_id', 'order_date', 'status', 'payment_method', 'discount_code', 'shipping_fee']

ORDER ITEMS
['order_id', 'product_id', 'quantity', 'unit_price', 'discount_amount']

PRODUCTS
['product_id', 'product_name', 'category', 'list_price', 'unit_cost']

Relations
- customer_id
- order_id
- product_id

# data info

### customer

In [10]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 3600 entries, 0 to 3599
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   customer_id          3600 non-null   int64
 1   signup_date          3600 non-null   str
 2   state                3600 non-null   str
 3   acquisition_channel  3600 non-null   str
dtypes: int64(1), str(3)
memory usage: 112.6 KB

In [53]:
customers.describe(include='all')

        customer_id signup_date state acquisition_channel
count   3600.000000        3600  3600                3600
unique          NaN         811    35                   6
top             NaN  2025-10-29    CA      organic_search
freq            NaN          17   451                1230
mean    1800.500000         NaN   NaN                 NaN
std     1039.374812         NaN   NaN                 NaN
min        1.000000         NaN   NaN                 NaN
25%      900.750000         NaN   NaN                 NaN
50%     1800.500000         NaN   NaN                 NaN
75%     2700.250000         NaN   NaN                 NaN
max     3600.000000         NaN   NaN                 NaN

### order items

In [12]:
order_items.info()

<class 'pandas.DataFrame'>
RangeIndex: 15608 entries, 0 to 15607
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         15608 non-null  int64
 1   product_id       15608 non-null  int64
 2   quantity         15608 non-null  int64
 3   unit_price       15409 non-null  float64
 4   discount_amount  15608 non-null  float64
dtypes: float64(2), int64(3)
memory usage: 609.8 KB

In [54]:
order_items.describe(include='all')

,order_id,product_id,quantity,unit_price,discount_amount
count,15608.000000,15608.000000,15608.000000,15409.000000,15608.000000
mean,104570.429011,1046.471040,1.244810,113.084088,3.201492
std,2659.674531,28.278148,0.577641,108.590935,11.154638
min,100001.000000,1001.000000,1.000000,7.990000,0.000000
25%,102269.750000,1020.000000,1.000000,49.990000,0.000000
50%,104554.500000,1048.000000,1.000000,86.090000,0.000000
75%,106867.250000,1073.000000,1.000000,141.740000,0.000000
max,109207.000000,1090.000000,4.000000,812.690000,196.560000

### orders

In [14]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 9245 entries, 0 to 9244
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        9245 non-null   int64
 1   customer_id     9245 non-null   int64
 2   order_date      9245 non-null   str
 3   status          9245 non-null   str
 4   payment_method  9245 non-null   str
 5   discount_code   1411 non-null   str
 6   shipping_fee    9245 non-null   float64
dtypes: float64(1), int64(2), str(4)
memory usage: 505.7 KB

In [55]:
orders.describe(include='all')

,order_id,customer_id,order_date,status,payment_method,discount_code,shipping_fee
count,9245.000000,9245.000000,9245,9245,9245,1411,9245.000000
unique,NaN,NaN,9206,3,4,3,NaN
top,NaN,NaN,2024-01-06 16:37:36,completed,credit_card,HOLIDAY20,NaN
freq,NaN,NaN,2,8490,5332,782,NaN
mean,104604.530882,1784.054840,NaN,NaN,NaN,NaN,1.544862
std,2657.471479,1062.469902,NaN,NaN,NaN,NaN,2.889826
min,100001.000000,2.000000,NaN,NaN,NaN,NaN,0.000000
25%,102304.000000,863.000000,NaN,NaN,NaN,NaN,0.000000
50%,104605.000000,1786.000000,NaN,NaN,NaN,NaN,0.000000
75%,106907.000000,2738.000000,NaN,NaN,NaN,NaN,0.000000
max,109207.000000,3600.000000,NaN,NaN,NaN,NaN,6.950000

### products

In [16]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    90 non-null     int64
 1   product_name  90 non-null     str
 2   category      90 non-null     str
 3   list_price    90 non-null     float64
 4   unit_cost     90 non-null     float64
dtypes: float64(2), int64(1), str(2)
memory usage: 3.6 KB

In [56]:
products.describe(include='all')

         product_id      product_name category  list_price   unit_cost
count     90.000000                90       90   90.000000   90.000000
unique          NaN                90       24         NaN         NaN
top             NaN  Brass Chef Knife  Kitchen         NaN         NaN
freq            NaN                 1       10         NaN         NaN
mean    1045.500000               NaN      NaN  134.378889   69.563222
std       26.124701               NaN      NaN  136.899512   76.820180
min     1001.000000               NaN      NaN    7.990000    4.760000
25%     1023.250000               NaN      NaN   52.490000   24.547500
50%     1045.500000               NaN      NaN   95.490000   49.275000
75%     1067.750000               NaN      NaN  151.490000   74.330000
max     1090.000000               NaN      NaN  773.990000  445.470000

# data handling

## missing values

In [18]:
customers.isnull().any()

customer_id            False
signup_date            False
state                  False
acquisition_channel    False
dtype: bool

In [19]:
order_items.isnull().sum()

order_id             0
product_id           0
quantity             0
unit_price         199
discount_amount      0
dtype: int64

In [20]:
orders.isnull().sum()

order_id             0
customer_id          0
order_date           0
status               0
payment_method       0
discount_code     7834
shipping_fee         0
dtype: int64

In [21]:
products.isnull().sum()

product_id      0
product_name    0
category        0
list_price      0
unit_cost       0
dtype: int64

## duplicates

In [26]:
customers.duplicated().any() # no duplicates
order_items.duplicated().any() # no duplicates
products.duplicated().any() # no duplicates
print(orders.duplicated().any()) # only orders has duplicate values 
print(orders.duplicated().sum())

True
38

## unique id

In [42]:
print(f'Customers:\nRows {len(customers)},\nUnique customer id:{customers['customer_id'].nunique()}\n')

print(f"Order Items:\nRows {len(customers)},\nUnique Order Items {order_items['order_id'].nunique()}\n ")

print(f'Orders:\nRows {len(orders)},\nUnique Orders {orders['order_id'].nunique()}\n')

print(f'Products:\nRows {len(products)},\nUnique product {products['product_id'].nunique()}')

Customers:
Rows 3600,
Unique customer id:3600

Order Items:
Rows 3600,
Unique Order Items 9207

Orders:
Rows 9245,
Unique Orders 9207

Products:
Rows 90,
Unique product 90

In [52]:
print(f'minimum: {orders['order_date'].min()},\nmaximum: {orders['order_date'].max()}')

minimum: 2024-01-01 09:24:45,
maximum: 2025-12-31 23:23:29

In [61]:
customers.columns.tolist()
orders.columns.tolist()
order_items.columns.tolist()
products.columns.tolist()


print(f'Customer: {customers.columns.tolist()}\n\nOrders: {orders.columns.tolist()}\n\nOrder items: {order_items.columns.tolist()}\n\nProducts: {products.columns.tolist()}')

Customer: ['customer_id', 'signup_date', 'state', 'acquisition_channel']

Orders: ['order_id', 'customer_id', 'order_date', 'status', 'payment_method', 'discount_code', 'shipping_fee']

Order items: ['order_id', 'product_id', 'quantity', 'unit_price', 'discount_amount']

Products: ['product_id', 'product_name', 'category', 'list_price', 'unit_cost']

# handling duplicated value

In [68]:
print(f"CUSTOMER ID CHECK:\nRows: {len(customers)}\nUnique ID {customers['customer_id'].nunique()}\nDuplicate ID {customers['customer_id'].duplicated().sum()}  ")

print(f"\nORDER ID CHECK\nRows: {len(orders)}\nUnique ID {orders['order_id'].nunique()}\nDuplicate ID {orders['order_id'].duplicated().sum()} ")


print(f"\nPRODUCT ID CHECK\nRows: {len(products)}\nUnique ID {products['product_id'].nunique()}\nDuplicate ID {products['product_id'].duplicated().sum()}")


print(f"\nORDER ITEM CHECK\nRows: {len(order_items)}\nUnique ID {order_items['order_id'].nunique()}\nDuplicate ID {order_items['order_id'].duplicated().sum()}")
print("Rows:", len(order_items))
print(
    "Duplicate order-product pairs:",
    order_items.duplicated(
        subset=["order_id", "product_id"]
    ).sum()
)

CUSTOMER ID CHECK:
Rows: 3600
Unique ID 3600
Duplicate ID 0

ORDER ID CHECK
Rows: 9245
Unique ID 9207
Duplicate ID 38

PRODUCT ID CHECK
Rows: 90
Unique ID 90
Duplicate ID 0

ORDER ITEM CHECK
Rows: 15608
Unique ID 9207
Duplicate ID 6401
Rows: 15608
Duplicate order-product pairs: 0